package com.aether.mobile

import android.app.Activity
import android.app.Application
import android.content.Context
import android.content.Intent
import android.net.VpnService
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import java.lang.ref.WeakReference

/**
 * Drives the system-wide VPN.
 *
 * The Rust side never calls into Java: it only flips two flags, which this
 * object polls. Everything Android specific - the consent dialog, the
 * VpnService lifetime, the tun descriptor - happens here.
 *
 * Consent is asked from a foreground activity, never from here: Android 10+
 * silently drops a background activity launch, which is how the old flow
 * ended up waiting out a timer with no dialog ever on screen. `begin()` parks
 * the consent intent, the activity lifecycle hook launches it the moment an
 * activity of this app is resumed, and the answer is read back from
 * VpnService.prepare while the poller keeps ticking. The generated
 * MainActivity is never touched.
 */
object AetherVpn {
    private const val POLL_MS = 300L
    private const val CONSENT_TIMEOUT_MS = 120_000L

    private val handler = Handler(Looper.getMainLooper())

    @Volatile private var appContext: Context? = null
    @Volatile private var hookInstalled = false

    /** The consent dialog to launch, parked until an activity is resumed. */
    @Volatile private var pendingConsentIntent: Intent? = null

    /** The dialog is on screen: its answer is now read back from prepare(). */
    private var consentLaunched = false
    private var consentDeadline = 0L
    private var resumedActivity: WeakReference<Activity>? = null

    private external fun nativePoll(): Int
    private external fun nativeOnTunReady(fd: Int): Int
    private external fun nativeReport(code: Int)

    init {
        runCatching { System.loadLibrary("aether_mobile_lib") }
            .recoverCatching { System.loadLibrary("aether_mobile") }
    }

    /** Called from the boot provider, before any activity exists. */
    fun bootstrap(context: Context) {
        appContext = context.applicationContext
        installActivityHook()
        handler.removeCallbacks(tick)
        handler.postDelayed(tick, POLL_MS)
    }

    /** True when the relay accepted the descriptor. */
    fun onTunReady(fd: Int): Boolean = nativeOnTunReady(fd) == 0

    fun report(code: Int) {
        runCatching { nativeReport(code) }
    }

    /**
     * Watches this app's own activities so the consent dialog can go up while
     * one of them is on screen. MainActivity is generated by the Tauri CLI and
     * is deliberately left alone, so the hook hangs off the Application.
     */
    private fun installActivityHook() {
        if (hookInstalled) return
        val app = appContext as? Application ?: return
        app.registerActivityLifecycleCallbacks(object : Application.ActivityLifecycleCallbacks {
            override fun onActivityResumed(activity: Activity) {
                resumedActivity = WeakReference(activity)
                launchParkedConsent()
            }

            override fun onActivityPaused(activity: Activity) {
                if (resumedActivity?.get() === activity) resumedActivity = null
            }

            override fun onActivityDestroyed(activity: Activity) {
                if (resumedActivity?.get() === activity) resumedActivity = null
            }

            override fun onActivityCreated(activity: Activity, state: Bundle?) {}
            override fun onActivityStarted(activity: Activity) {}
            override fun onActivityStopped(activity: Activity) {}
            override fun onActivitySaveInstanceState(activity: Activity, state: Bundle) {}
        })
        hookInstalled = true
    }

    /** Starts the tun service once consent exists. */
    fun startServiceNow() {
        val context = appContext ?: return report(2)
        runCatching { context.startService(Intent(context, AetherVpnService::class.java)) }
            .onFailure { report(2) }
    }

    private val tick = object : Runnable {
        override fun run() {
            runCatching {
                if (consentLaunched) checkConsent()
                val work = nativePoll()
                if (work and 1 != 0) begin()
                if (work and 2 != 0) stopService()
            }
            handler.postDelayed(this, POLL_MS)
        }
    }

    /**
     * Checks the grant: with one in hand the service starts at once, otherwise
     * the consent intent is parked for the next resumed activity, which puts
     * the dialog on screen while the user is still looking at the app.
     */
    private fun begin() {
        val context = appContext ?: return report(4)
        val consent = runCatching { VpnService.prepare(context) }.getOrNull()
        if (consent == null) {
            report(0)
            startServiceNow()
            return
        }
        pendingConsentIntent = consent
        launchParkedConsent()
    }

    /**
     * Launches the parked dialog from a resumed activity of this app. A launch
     * from an application context is exactly what Android 10+ drops, so with
     * no resumed activity the intent simply stays parked.
     */
    private fun launchParkedConsent() {
        if (consentLaunched) return
        val intent = pendingConsentIntent ?: return
        val activity = resumedActivity?.get() ?: return
        pendingConsentIntent = null
        consentLaunched = true
        consentDeadline = System.currentTimeMillis() + CONSENT_TIMEOUT_MS
        runCatching { activity.startActivity(intent) }
            .onFailure {
                consentLaunched = false
                report(4)
            }
    }

    /**
     * The dialog is up: prepare() reports null the instant the user accepts
     * and keeps returning an intent while it is unanswered (or was refused),
     * so the deadline is what ends the wait.
     */
    private fun checkConsent() {
        val context = appContext ?: return
        val granted = runCatching { VpnService.prepare(context) == null }.getOrDefault(false)
        if (granted) {
            consentLaunched = false
            report(0)
            startServiceNow()
            return
        }
        if (System.currentTimeMillis() > consentDeadline) {
            consentLaunched = false
            report(1)
        }
    }

    private fun stopService() {
        val context = appContext ?: return
        runCatching { context.stopService(Intent(context, AetherVpnService::class.java)) }
    }
}
